server {
    listen 80;
    server_name localhost;
    
    # Comprimir archivos para mayor velocidad
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # CRUCIAL PARA VUE ROUTER:
        # Si no encuentra el archivo, sirve index.html para que Vue maneje la ruta
        try_files $uri $uri/ /index.html;
    }

    # Proxy Reverso para Producción
    # (En desarrollo esto lo maneja vite.config.js, en prod lo maneja Nginx)
    location /api/ {
        # 'core-service' es el nombre del servicio en docker-compose
        proxy_pass http://core-service:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Reescribir la URL si tu backend espera /v1/... sin /api/
        # rewrite ^/api/(.*) /$1 break; 
    }
}